### ISSUE TITLE
ezc3d for Python failed to open a c3d file : Bad c3d formatting: unspecified iostream_category error

### ISSUE THREAD

**Issue by NLantos** [pyomeca/ezc3d#233]
Hello and thank you for sharing your code. 

We try to open via ezc3d with the python interface a c3d file and it fails with the following error:

> Traceback (most recent call last):
>   File "/Users/lantos/PycharmProjects/Expe_Stage_Kelly/test_ezc3d.py", line 12, in <module>
>     c = c3d(filename)
>   File "/opt/miniconda3/lib/python3.9/site-packages/ezc3d/__init__.py", line 128, in __init__
>     self.c3d_swig = ezc3d.c3d(path)
>   File "/opt/miniconda3/lib/python3.9/site-packages/ezc3d/ezc3d.py", line 1686, in __init__
>     _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))
> RuntimeError: Bad c3d formatting: unspecified iostream_category error

The file was generated from Optitrack file and is readable by the python module c3d with no execution error.

The file is rather big 1.53 Gb, how do you want to proceed so that I transfer it to you? 

My configuration is a Macbook pro 2.6 GHz Intel Core i7 quatre cœurs and Python 3.9. ezc3d was installed with miniconda.

Thanks in advance.

**Comment by pariterre** [comment]
Hi @NLantos !
I can see why it does not work. You can drop the file at this address! I have a look ASAP :)
https://cloud.pariterre.net/index.php/s/K9y6Nn9MimF72MQ

**Comment by NLantos** [comment]
Hi @pariterre, 
Thank you for your quick response.
I have downloaded the file "bloc3_orientation_ok.c3d" through the link you sent me.
Best Regards

**Comment by pariterre** [comment]
Hi @NLantos !
Sorry for taking so long, I actually forgot about this issue..

So I had a look at your file, and it is indeed corrupted. Not in the sense that the data are not there, but in the sense that the parameters are not stored properly.
There is an easy fix.. in the reading process of parameter, I do a sanity check over the pointer in the file with the predicted position of the next parameter. If I bypass the check and replace it by a break, it seems to work fine
 if (file.tellg() != nextParamByteInFile)

I'll see if I can safely push this fix!

**Comment by pariterre** [comment]
Sorry I miss clicked on resolved

**Comment by NLantos** [comment]
Sorry for the delay and thank you for your answer. 
Do you know when you will be able to integrate this change if of course it is safe to push it?
I have another c3d file that produced the same error. Would you like me to send it to you for testing?
Thank you in any case.

**Comment by pariterre** [comment]
Hi @NLantos !
I'll make a fix for another Issue next weekend, I'll have a deeper look to see if this check can actually be ignored safely. So I'd say next weekend I should push a fix :)

**Comment by pariterre** [comment]
I pushed the fix, it should be on conda in few hours :)

**Comment by NLantos** [comment]
Hello @pariterre  , 
As mentioned in the PR #238, I was late. I'm really sorry. 
I have re-run the case for this PR and I still get the same error.

> /opt/miniconda3/bin/python.app /Users/lantos/PycharmProjects/Expe_Stage_Kelly/run_PP_ezc3d.py

> ezc3d 1.5.0
> input_filename 0_Inputs/4_Optitrack/P5/bloc3_orientation_ok.c3d
> Reading ezc3d 2022-09-15 17:24:55.162406
> Traceback (most recent call last):
>   File "/Users/lantos/PycharmProjects/Expe_Stage_Kelly/run_PP_ezc3d.py", line 75, in <module>
>     c = c3d(input_filename)
>   File "/opt/miniconda3/lib/python3.9/site-packages/ezc3d/__init__.py", line 128, in __init__
>     self.c3d_swig = ezc3d.c3d(path, ignore_bad_formatting)
>   File "/opt/miniconda3/lib/python3.9/site-packages/ezc3d/ezc3d.py", line 1901, in __init__
>     _ezc3d.c3d_swiginit(self, _ezc3d.new_c3d(*args))
> RuntimeError: Bad c3d formatting: unspecified iostream_category error

Could it be that your patch was not integrated in this version 1.5.0?
Thanks in advance.
