### ISSUE TITLE
Installing from Pypi on a mac fails

### ISSUE THREAD

**Issue by felixchenier** [pyomeca/ezc3d#349]
Sorry @pariterre , I have to make this issue :-)

```
conda create -n test python=3.12
conda activate test
pip install ezc3d
```

gives:

```
Collecting ezc3d
  Downloading ezc3d-1.5.15.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/felix/opt/miniconda3/envs/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/felix/opt/miniconda3/envs/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/felix/opt/miniconda3/envs/test/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-bx13_t6n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-bx13_t6n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-bx13_t6n/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-ukb40id_/ezc3d_9612d24de18445558850d5f75d98b719/CMakeLists.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Macbook Pro 2020 Intel, macOS Sonoma.

**Comment by pariterre** [comment]
Yep, this relates to #345  which I am currently (at the very moment) fixing :)

**Comment by felixchenier** [comment]
Bonne chance! ;-)

**Comment by pariterre** [comment]
It should be resolved by now, please confirm! :D

**Comment by felixchenier** [comment]
On my side it still doesn't work, it tries to compile it instead of downloading the precompiled wheel. But by checking on Pypi's ezc3d files, I see that wheels are available for macOS on Python 3.12, but only for ARM Macs, not for Intel Macs (I have an Intel Mac). Now it's a matter of choice to support Intel Macs or not - in 5 years there won't be much still around.

Unfortunately I don't have XCode installed since I exclusively work in Python, and therefore I could not test if compiling works.

I put the output for reference here. 

```
pip install ezc3d
```

```
Collecting ezc3d
  Downloading ezc3d-1.5.16.tar.gz (151 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from ezc3d)
  Using cached numpy-2.1.3-cp312-cp312-macosx_14_0_x86_64.whl.metadata (62 kB)
Using cached numpy-2.1.3-cp312-cp312-macosx_14_0_x86_64.whl (6.6 MB)
Building wheels for collected packages: ezc3d
  Building wheel for ezc3d (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ezc3d (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [138 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 11.0.3.11030032
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-5mp30n65/overlay/lib/python3.12/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler
      
          "/Library/Developer/CommandLineTools/usr/bin/cc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-xeabs6v_/ezc3d_63516d7ca82244fbb74b3c55829ff410/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fM2b1s'
      
          Run Build Command(s): ninja -v cmTC_7572a
          [1/2] /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=14.0 -MD -MT CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o -c /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-xeabs6v_/ezc3d_63516d7ca82244fbb74b3c55829ff410/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fM2b1s/testCCompiler.c
          FAILED: CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=14.0 -MD -MT CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_7572a.dir/testCCompiler.c.o -c /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-xeabs6v_/ezc3d_63516d7ca82244fbb74b3c55829ff410/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-fM2b1s/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=14.0'
          ninja: build stopped: subcommand failed.
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.10 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
        to tell CMake that the project requires at least <min> but has been updated
        to work with policies introduced by <max> or earlier.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 11.0.3.11030032
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-5mp30n65/overlay/lib/python3.12/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler
      
          "/Library/Developer/CommandLineTools/usr/bin/cc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-xeabs6v_/ezc3d_63516d7ca82244fbb74b3c55829ff410/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zEKg5l'
      
          Run Build Command(s): /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-build-env-5mp30n65/overlay/lib/python3.12/site-packages/cmake/data/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_989c1/fast
          /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_989c1.dir/build.make CMakeFiles/cmTC_989c1.dir/build
          Building C object CMakeFiles/cmTC_989c1.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=14.0 -MD -MT CMakeFiles/cmTC_989c1.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_989c1.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_989c1.dir/testCCompiler.c.o -c /private/var/folders/7v/g5_ntzfx35v4ck07wflynw640000gp/T/pip-install-xeabs6v_/ezc3d_63516d7ca82244fbb74b3c55829ff410/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zEKg5l/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=14.0'
          make[1]: *** [CMakeFiles/cmTC_989c1.dir/testCCompiler.c.o] Error 1
          make: *** [cmTC_989c1/fast] Error 2
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------
      
                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.
      
                      Building MacOSX wheels for Python 3.12 requires XCode.
      Get it here:
      
        https://developer.apple.com/xcode/
      
                      ********************************************************************************
      [end of output]
```

**Comment by pariterre** [comment]
I see! Just added intel, it is going to take about an hour before I know if it worked

**Comment by pariterre** [comment]
I think intel for Mac is now available :)
Can you confirm?

**Comment by felixchenier** [comment]
Working! 🥳
